### ISSUE TITLE
Complete rebuild. Version... 4?

### ISSUE THREAD

**Issue by citricsquid** [citricsquid/widget#42]
At its core the project should have clear separation between fetching data (request from curse.com, parse) and displaying data. Data that is out of date is better than no data. This project is blindingly simple, it should not be so unreliable.

The project should be rebuilt with reliability at the core, and a full error management layer. The API should be monitored using [Runscope](https://runscope.com).

**Comment by citricsquid** [comment]
https://github.com/thephpleague/fractal

**Comment by citricsquid** [comment]
API goals:

* Run an API with 100% availability
* Provide an easy to use system so that anyone can run their own API server
* Every request should receive a response, fresh data (<1 hour old) is ideal, stale data (>1 hour old) is okay, "Sorry we don't have data" is bad, no response is terrible end of the world no thank you

A complex high availability system using a data store, load balancer(s) and multiple web servers split across multiple zones with AWS/GCP would be a good option for high availability with a traditional API, but I don't know if it's the right choice for this API. This system does not have any responsibility for any data, it is only responsible for fetching data from a third party and then serving data to consumers, meaning the worst case scenario is... we can't respond to requests: data can't be lost by this system. For high availability it can be as easy as running the self contained system in 2 separate places (eg: 1 in AWS, 1 in GCP) and failing over to the second if the first fails, maybe using Route 53 health checks? Absolute worst case scenario is if both servers disappear from the internet, in which case another can be spun up in a separate data centre in minutes. A system designed like this would meet availability needs and the simple to run goal for third parties.

How the API might work:

1. A request is made to the API for $project
2. The system checks if it has any data for $project
3. If yes the data is served
4. If $project data is not available then $project is added to a queue to be fetched and a response is given, like "Project data not yet available, try again in 60 seconds".

The queue would work by going through each project in order, fetch the project page from curse.com, 
parse the HTML to retrieve the properties, add them to the cache with a "last retrieved at" time. A job would run every 60 seconds that checked the cache for projects that were considered stale (based on "last retrieved time" being greater than a configurable amount (probably 60 minutes)) and add the project back to the queue.

This system is flawed in that when it is first brought online there will be requests to every project seeing responses telling them that data is not available until it is fetched, however because there are a finite number of curse.com hosted projects used by people making requests to the API we could potentially store a list of projects for the app to fetch by default when it starts up. This list could be gathered based on requests already being made to the API, or even by grabbing the popular projects from curse.com.

**Comment by citricsquid** [comment]
The remainder of the project would be pretty straight forward. The widget would be a consumer of the API that renders the data in a pretty way, so that too could be a self contained service that anyone could run if they wanted to, built using go. The project homepage could just be a static HTML job, using Javascript for the "create a widget" wizard, which also consumes the API. Simple!

Homepage: curse.mcf.li
Widget: widget.curse.mcf.li
API: api.curse.mcf.li

I'd like to abandon the mcf.li domain, especially given this project is usable for *all* curse hosted projects (world of warcraft, terraria, I recently discovered that a popular Kerbal Space Program addon manager is planning to use the API...) so a more generic name would be ideal, but I don't want to run into issues with trademarks and whatever, so maybe something like "addon.ninja" or something dumb like that. I don't know. I don't hate mcf.li so we can keep it for now but if a better idea comes up, migrate! hurray!

**Comment by citricsquid** [comment]
Something that is worth revisiting is what the current API does. At the moment it just pulls from curse.com, and doesn't include some things, which is suboptimal. [mods.curse.com](http://mods.curse.com) is essentially a consumer frontend to curseforge, which contains more/different information. For example: http://mods.curse.com/customization/minecraft/229041-lucky-block-spiral-1-8-lucky-block-addon and http://minecraft.curseforge.com/projects/lucky-block-spiral-1-8-lucky-block-addon, same project, different information.

The differences between mods.curse.com and curseforge.com:

* mods.curse.com only displays "beta" and "release" files, it does not display "alpha" files
* both sites have their own separate comments
* the changelog listed on curse.com is only for the latest file
* each file listed on curseforge has its own changelog
* curseforge info is split across multiple pages, curse.com is all on one page

**Comment by LukeHandle** [comment]
> A job would run every 60 seconds that checked the cache for projects that were considered stale (based on "last retrieved time" [...]
The issue I can forsee is it being costly to list out all (internally) registered projects before calculating whether they are stale. The other idea I had was after each project is requested, you create a go routine for that request. This routine then sleeps until it needs to re-queue the project (say, a 60 minute sleep) before exiting.

I'm not sure how many unique projects you would be tracking and if that many go routines would be inefficient. The same considerations would have to be given to iterating though that much data every minute ;) 

There is an example in the `imgd` project. We don't use that in production though as we share a Redis backend between the nodes (I did used to run it without issue though). 

https://github.com/minotar/imgd/blob/master/cache_memory.go#L95-97

> `AfterFunc` waits for the duration to elapse and then calls f in its own goroutine. It returns a Timer that can be used to cancel the call using its Stop method.

The complication would then be rescheduling the re-requests at server start. It would likely need a one time (costly) run through of all projects to initialize the sleep processes. It would know how long it needed to set each to sleep for so there shouldn't be a bust I'm queued requests. 

Thoughts?
