### ISSUE TITLE
Minecraft Mods with Multiple Game Versions only show up on a Single Version

### ISSUE THREAD

**Issue by TehSomeLuigi** [citricsquid/widget#43]
Hi, one issue I noticed with the widget and its JSON API:

Mods such as The One Probe which have versions which are binary-compatible with multiple game versions[1].
These versions only show up for a single game version[2] and are not associated with the other game version(s).[3]

As a result, users and API-users are given incomplete information when they look for the latest version of the mod on a given Minecraft version since the mod may not be listed under it.

I can't see any decent workaround other than scraping CurseForge for the information, but even then the version information is hidden behind a tooltip and isn't that easy to extract, from my cursory look.

[1] https://minecraft.curseforge.com/projects/the-one-probe/files/2397023
[2] http://widget.mcf.li/mc-mods/minecraft/245211-the-one-probe.json
[3] http://widget.mcf.li/mc-mods/minecraft/245211-the-one-probe?version=1.10.2

**Comment by citricsquid** [comment]
Thank you for submitting this issue -- apologies for the delay in responding.

The widget (and api) are constrained to sourcing data from curse.com, as while curseforge.com does contain more information, like alpha files, that information is spread over what can be dozens of pages, which would greatly increase the complexity of this project and the resources required to run it. Long term the intent is for the widget to go away when it is succeeded by some sort of official curseforge widget.

Although this is a bug, it's not something that will be fixed therefore I am closing the issue.
